// Generated by CoffeeScript 1.6.3
/*
# Example of how to use this module.
#
# Required:
# A USB Ant stick (V3 is provided with the Vector Pedals, V2 can be purchased online and changed to GarminStick2 below)
*/(function(){var e,t,n,r,i=this;t=require("./node-ant").GarminStick3;e=require("./node-ant").VectorSensor;n=new t;n.open();r=new e(n);r.on("powerdata",function(e){return console.log(e.power.instantaneous)});r.attach(0,5800);setTimeout(function(e){return r.detachAll()},5e3)}).call(this);