# Do not edit this file directly.  For code abstraction purposes, create a new partial (leading underscore)
# and add that file to this list.


# @codekit-prepend "_Ant.coffee"
# @codekit-prepend "_Constants.coffee"

@Ant = new Ant()