# Do not edit this file directly.  For code abstraction purposes, create a new partial (leading underscore)
# and add that file to this list.

# @codekit-prepend "_Constants.coffee"
# @codekit-prepend "_Messages.coffee"
# @codekit-prepend "_Ant.coffee"
# @codekit-prepend "_Driver.coffee"
# @codekit-prepend "_Stick.coffee"
# @codekit-prepend "_Sensor.coffee"
# @codekit-prepend "_PowerSensor.coffee"
# @codekit-prepend "_SpeedAndCadenceSensor.coffee"

module.exports = new Ant();

  