# Do not edit this file directly.  For code abstraction purposes, create a new partial (leading underscore)
# and add that file to this list.

# @codekit-prepend "_Constants.coffee"
# @codekit-prepend "_Messages.coffee"
# @codekit-prepend "_Ant.coffee"
# @codekit-prepend "_Driver.coffee"
# @codekit-prepend "_Stick.coffee"
# @codekit-prepend "_Sensor.coffee"
# @codekit-prepend "_PowerSensor.coffee"
# @codekit-prepend "_SpeedAndCadenceSensor.coffee"

module.exports = new Ant();

### This is sample code to run in a node seesion to test fore recieving instantaneous power ###
# var Stick = require('./node-ant').GarminStick3
# var Sensor = require('./node-ant').VectorSensor
# 
# var stick = new Stick();
# stick.open();
# 
# var vector = new Sensor(stick);
# vector.on('powerdata', function(data){ console.log(data.power.instantaneous); });
# vector.attach(0, 05800);
# 
# vector.detachAll();
  